# -*- coding: utf-8 -*-
"""2009010.42_Assign_02ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gQ8Gl8S36l9mag_oFdWnqjmVcoowsgMe
"""

import ast

def build_syntax_tree(expression):
  # Parse the expression into an AST using the parse function from the ast module
  tree = ast.parse(expression)

  # Return the AST
  return tree

expression = "3+(5*2)"
tree = build_syntax_tree(expression)
print(ast.dump(tree))
# Output:
# Module(body=[Expr(value=BinOp(left=Num(n=3), op=Add(), right=BinOp(left=Num(n=5), op=Mult(), right=Num(n=2))))])